### ISSUE TITLE
E/PlaceAPI: Cannot process JSON results

### ISSUE THREAD

**Issue by emrekilincarslan** [mukeshsolanki/Places-AutoComplete-EditText#18]
2020-08-14 00:29:28.268 23436-23501/com.ruzgar.rainbow E/PlaceAPI: Cannot process JSON results
    org.json.JSONException: No value for plus_code
        at org.json.JSONObject.get(JSONObject.java:399)
        at org.json.JSONObject.getJSONObject(JSONObject.java:619)
        at in.madapps.placesautocomplete.PlaceAPI.parseDetailsData(PlaceApi.kt:171)
        at in.madapps.placesautocomplete.PlaceAPI.access$parseDetailsData(PlaceApi.kt:25)
        at in.madapps.placesautocomplete.PlaceAPI$fetchPlaceDetails$1.run(PlaceApi.kt:70)
        at java.lang.Thread.run(Thread.java:919)

**Comment by mukeshsolanki** [comment]
Have you tried the latest version??

**Comment by mukeshsolanki** [comment]
@emrekilincarslan any update on this?

**Comment by ArslanKhan99** [comment]
what is the latest version?

**Comment by haris15** [comment]
same issue reproduce on some address. any one found any solution ?
